### ISSUE TITLE
How to achieve this?

### ISSUE THREAD

**Issue by maxfridbe** [pvginkel/CSharpSyntax#1]
I Tried several ways to achieve 

` pubic int bob {get;set;} =3;`

seems like initializer not allowed

**Comment by pvginkel** [comment]
This is not possible because the library doesn't support this. This library is not actively developed. If you require support for this, I suggest using Roslyn. Roslyn is a bit more verbose to use, but does support all C# language features and does support building C# code in a way similar to what this library supports.
